name: CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9"]

    steps:
      # 1.  checkout repo
      - uses: actions/checkout@v4

      # 2.  set up the desired Python & enable pip caching
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # 3.  install project + test deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install your package in editable mode
          pip install -e .
          # install test-only deps
          pip install pytest aiounittest cbor2 
          # (add mypy/coverage/flake8/etc. here if you use them)

      # 4.  run the full test-suite
      - name: Run pytest
        run: |
          pytest -q